use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let assets = Path::new(&manifest).join("assets");
    let out = std::env::var("OUT_DIR").unwrap();
    let out_file = Path::new(&out).join("embedded_assets.rs");

    println!("cargo:rerun-if-changed=assets");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if assets.exists() {
        walk(&assets, &mut entries);
    }
    entries.sort();

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs — khong sua tay\n");
    code.push_str("use bevy::asset::io::embedded::EmbeddedAssetRegistry;\n");
    code.push_str("use std::path::{Path, PathBuf};\n\n");
    code.push_str("pub fn register_embedded_assets(reg: &EmbeddedAssetRegistry) {\n");
    for (rel, abs) in &entries {
        let abs_str = abs.to_string_lossy().replace('\\', "/");
        let rel_norm = rel.replace('\\', "/");
        code.push_str(&format!(
            "    reg.insert_asset(\n        PathBuf::from(r\"{abs}\"),\n        Path::new(r\"{rel}\"),\n        include_bytes!(r\"{abs}\").as_slice(),\n    );\n",
            abs = abs_str,
            rel = rel_norm,
        ));
    }
    code.push_str("}\n");
    code.push_str(&format!(
        "pub const EMBEDDED_ASSET_COUNT: usize = {};\n",
        entries.len()
    ));

    fs::write(&out_file, code).unwrap();
}

fn walk(dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            walk(&p, out);
        } else if p.is_file() {
            let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
            let rel = p
                .strip_prefix(&manifest)
                .unwrap_or(&p)
                .to_string_lossy()
                .to_string();
            out.push((rel, p.clone()));
        }
    }
}
